// apps/web/src/components/Header.svelte
<script lang="ts">

	import UserMenu from './UserMenu.svelte';

</script>

<div>
	<div class="flex flex-row items-center justify-between px-4 py-2 md:px-6">
		<nav class="flex gap-4 text-lg">
			<a href="/" class="hover:text-neutral-400 transition-colors">Home</a>
			<a href="/dashboard" class="hover:text-neutral-400 transition-colors">Dashboard</a>
		</nav>
		<div class="flex items-center gap-2">
            <UserMenu />
		</div>
	</div>
	<hr class="border-neutral-800" />
</div>

// apps/web/src/components/header.tsx
import { For } from "solid-js";

import UserMenu from "./user-menu";

export default function Header() {
  const links = [
    { to: "/", label: "Home" },
    { to: "/dashboard", label: "Dashboard" },
  ];

  return (
    <div>
      <div class="flex flex-row items-center justify-between px-2 py-1">
        <nav class="flex gap-4 text-lg">
          <For each={links}>{(link) => <a href={link.to}>{link.label}</a>}</For>
        </nav>
        <div class="flex items-center gap-2">
          <UserMenu />
        </div>
      </div>
      <hr />
    </div>
  );
}
