// apps/web/src/routes/dashboard/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { authClient } from '$lib/auth-client';

	const sessionQuery = authClient.useSession();


	$effect(() => {
		if (!$sessionQuery.isPending && !$sessionQuery.data) {
			goto('/login');
		}
	});

</script>

{#if $sessionQuery.isPending}
	<div>Loading...</div>
{:else if !$sessionQuery.data}
	<div>Redirecting to login...</div>
{:else}
	<div>
		<h1>Dashboard</h1>
		<p>Welcome {$sessionQuery.data.user.name}</p>
	</div>
{/if}

// apps/web/src/routes/dashboard.tsx
import { useNavigate } from "@solidjs/router";
import { createEffect, Show } from "solid-js";

import { useSession } from "~/lib/auth-client";

export default function Dashboard() {
  const navigate = useNavigate();
  const session = useSession();

  createEffect(
    () => !session().isPending && !session().data,
    (shouldRedirect) => {
      if (shouldRedirect) {
        navigate("/login", { replace: true });
      }
    },
  );

  return (
    <Show when={!session().isPending && session().data} fallback={<p>Loading...</p>}>
      <div>
        <h1>Dashboard</h1>
        <p>Welcome {session().data?.user.name}</p>
      </div>
    </Show>
  );
}
